services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.24.1

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  # Build all images
  - docker-compose build
  # Build OpenPLC Editor image
  - docker-compose --file openplc-editor/docker-compose.yml build
  # Build OPC UA images
  - docker-compose --file opcua/docker-compose.yaml build
  # List images
  - docker images
