version: '3.4'
services:
  mosquitto:
    image: eclipse-mosquitto
    stdin_open: true
    tty: true
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/logs
    ports:
      - "1883:1883"
      - "9001:9001"
 
  modbus-mqtt-bridge:
    build:
      context: .
      dockerfile: modbus-mqtt-bridge/Dockerfile
      args:
        http_proxy: "${http_proxy:-}"
        https_proxy: "${https_proxy:-}"
    image: modbus-mqtt-bridge
    stdin_open: true
    tty: true
    command: bash

  openplc:
    build:
      context: .
      dockerfile: openplc/Dockerfile
      args:
        http_proxy: "${http_proxy:-}"
        https_proxy: "${https_proxy:-}"
    image: openplc
    stdin_open: true
    tty: true
    # command: bash
    ports:
      - "8080:8080"
    privileged: true

  scadabr:
    build:
      context: .
      dockerfile: scadabr/Dockerfile
      args:
        http_proxy: "${http_proxy:-}"
        https_proxy: "${https_proxy:-}"
    image: scadabr
    stdin_open: true
    tty: true
    # command: bash
    ports:
      - "9090:9090"

  node-red:
    build:
      context: node-red
      dockerfile: Dockerfile
      args:
        http_proxy: "${http_proxy:-}"
        https_proxy: "${https_proxy:-}"
    image: node-red
    stdin_open: true
    tty: true
    # command: bash
    ports:
      - "1880:1880"
    depends_on:
      - mosquitto
    environment:
      - DEBUG=contribModbus*

  opcua-server:
    build:
      context: opcua-server
      dockerfile: Dockerfile
      args:
        http_proxy: "${http_proxy:-}"
        https_proxy: "${https_proxy:-}"
    image: opcua-server
    stdin_open: true
    tty: true

  opcua-client:
    build:
      context: opcua-client
      dockerfile: Dockerfile
      args:
        http_proxy: "${http_proxy:-}"
        https_proxy: "${https_proxy:-}"
    image: opcua-client
    stdin_open: true
    tty: true
    environment:
      - OPCUA_SERVER_ADDR=opcua-server
      - OPCUA_SERVER_PORT=4840

  opcua-pubsub:
    build:
      context: opcua-pubsub
      dockerfile: Dockerfile
      args:
        http_proxy: "${http_proxy:-}"
        https_proxy: "${https_proxy:-}"
    image: opcua-pubsub
    stdin_open: true
    tty: true
    depends_on:
      - mosquitto

  clients:
    build:
      context: .
      dockerfile: clients/Dockerfile
      args:
        http_proxy: "${http_proxy:-}"
        https_proxy: "${https_proxy:-}"
    image: clients
    stdin_open: true
    tty: true
    command: bash

volumes:
  mosquitto-data:
  mosquitto-log:
