version: '3.4'
services:
  mosquitto:
    image: eclipse-mosquitto
    stdin_open: true
    tty: true
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/logs

    ports:
      - "1883:1883"
      - "9001:9001"
 
  modbus-mqtt-bridge:
    build:
      context: .
      dockerfile: modbus-mqtt-bridge/Dockerfile
      args:
        http_proxy: "${http_proxy}"
        https_proxy: "${https_proxy}"
    image: openvino-runtime
    stdin_open: true
    tty: true
    command: bash

  openplc:
    build:
      context: .
      dockerfile: openplc/Dockerfile
      args:
        http_proxy: "${http_proxy}"
        https_proxy: "${https_proxy}"
    image: openplc
    stdin_open: true
    tty: true
    command: bash
    ports:
      - "8080:8080"

  scadabr:
    build:
      context: .
      dockerfile: scadabr/Dockerfile
      args:
        http_proxy: "${http_proxy}"
        https_proxy: "${https_proxy}"
    image: scadabr
    stdin_open: true
    tty: true
    command: bash

  clients:
    build:
      context: .
      dockerfile: clients/Dockerfile
      args:
        http_proxy: "${http_proxy}"
        https_proxy: "${https_proxy}"
    image: clients
    stdin_open: true
    tty: true
    command: bash

volumes:
  mosquitto-data:
  mosquitto-log:
