version: '3.4'
services:
  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/logs
    ports:
      - "1883:1883"
      - "9001:9001"
 
  openplc:
    build:
      context: .
      dockerfile: openplc/Dockerfile
      args:
        http_proxy: "${http_proxy:-}"
        https_proxy: "${https_proxy:-}"
    image: openplc
    ports:
      - "8080:8080"
    privileged: true

  scadabr:
    build:
      context: .
      dockerfile: scadabr/Dockerfile
      args:
        http_proxy: "${http_proxy:-}"
        https_proxy: "${https_proxy:-}"
    image: scadabr
    ports:
      - "9090:9090"

  node-red:
    build:
      context: node-red
      dockerfile: Dockerfile
      args:
        http_proxy: "${http_proxy:-}"
        https_proxy: "${https_proxy:-}"
    image: node-red
    ports:
      - "1880:1880"
    depends_on:
      - mosquitto
    environment:
      - DEBUG=contribModbus*

volumes:
  mosquitto-data:
  mosquitto-log:
