version: '3.4'
services:

  openplc-editor:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        http_proxy: "${http_proxy:-}"
        https_proxy: "${https_proxy:-}"
    image: openplc-editor
    stdin_open: true
    tty: true
    environment:
      - DISPLAY
    volumes:
      - "${HOME}/.Xauthority:/root/.Xauthority:rw"
      - ./projects:/root/projects
    network_mode: "host"
    privileged: true