version: '3.4'
services:

  openplc-editor:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        http_proxy: "${http_proxy:-}"
        https_proxy: "${https_proxy:-}"
    image: openplc-editor
    environment:
      - DISPLAY
    volumes:
      - "${HOME}/.Xauthority:/root/.Xauthority:rw"
      - ./projects:/root/projects